### ISSUE TITLE
video

### ISSUE THREAD

**Issue by Mrugalla** [suzumushi0/AudioQAM_binary#1]
hey :)

there is no issue with this plugin.
i just wanted to tell you that i made a video about it and i couldn't find an email address or anything:
https://youtu.be/VdnJFwAKm5E

feel free to close this "issue" again :D

**Comment by suzumushi0** [comment]
Mrugalla,

Thank you so much. It is just 3 days passed since I released AudioQAM. :-)

A quick comment.
Do you know Valhalla Freq Echo? If the feedback loop is suppressed, it is a Bode frequency shifter.

[https://valhalladsp.com/shop/delay/valhalla-freq-echo/](url)
[https://valhalladsp.com/2009/05/18/frequency-shifting-10-years-later/?](url)
